name: Deploy to All-Inkl (Development)

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Deploy to All-Inkl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Deploy to All-Inkl (Development)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**